config/routes.rb
PhotoApp::Application.routes.draw do
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :users
  resources :sessions

  root :to => 'articles#index'
  resources :articles
end

app/models/article.rb
class Article < ActiveRecord::Base
  has_many :tags
  has_many :users, :through => :tags

  validates :name, presence: true
  validates :content, presence: true

  has_attached_file :photo, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png",
    :url => "/assets/products/:id/:style/:basename.:extension",
    :path => ":rails_root/public/assets/products/:id/:style/:basename.:extension"
  validates_attachment_content_type :photo, :content_type => /\Aimage\/.*\Z/
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  belongs_to :user
  belongs_to :article
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :tags
  has_many :articles, :through => :tags

  has_secure_password
  validates_uniqueness_of :email
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def authorize
    redirect_to login_url, alert: "Not authorized" if current_user.nil?
  end

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

before_action :authorize, only: [:edit, :update]

  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to articles_path
    else
      render 'new'
    end
  end

  def show
    @users = User.all
    @article = Article.find(params[:id])
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path
  end

  private
    def article_params
      params.require(:article).permit(:name, :content, :author_name, :photo)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: "Logged in!"
    else
      flash.now.alert = "Email or password is invalid."
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save

      session[:user_id] = @user.id
      redirect_to root_url, notice: "Thank you for signing up!"
    else
      render "new"
    end
  end

  private
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_form.html.erb
<%= render("layouts/errors", :object => @article) %>

<%= form_for @article, :html => { :multipart => true } do |f| %>
  <div class="form-group">
    <%= f.label :name %></br>
    <%= f.text_field :name %>
  </div>
  <div class="form-group">
    <%= f.label :content %></br>
    <%= f.text_area :content %>
  </div>
  <div class="form-group">
    <%= f.label :author_name %></br>
    <%= f.text_field :author_name %>
  </div>
  <div class="form-group">
    <%= f.label :photo, "Photo" %>
    <%= f.file_field :photo %>
  </div>
  <%= f.submit(:class => "btn btn-primary") %>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render 'form' %></br>

<%= link_to "Homepage", articles_path, :class => "btn btn-primary" %>

app/views/articles/index.html.erb
<h1>Articles</h1>

<% @articles.each do |article| %>
  <h3><%= link_to article.name, article_path(article) %></h3>
  <p><%= image_tag article.photo.url(:thumb) %></p>
  <p>by <%= article.author_name %> on <%= article.published_at %></p>
  <p><%= article.content %></p>
<% end %>
<hr>
<%= link_to "New article", new_article_path, :class => "btn btn-primary" %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form' %></br>

<%= link_to "Homepage", articles_path, :class => "btn btn-primary" %>

app/views/articles/show.html.erb
<h1><%= @article.name %></h1>
  <p>by <%= @article.author_name %> on <%= @article.published_at %></p>
  <p><%= image_tag @article.photo.url(:medium) %></p>
  <p><%= @article.content %></p>
<hr>
<p><%= link_to "Edit Article", edit_article_path(@article), :class => "btn btn-primary" %></p>
<p><%= link_to "Delete Article", article_path(@article),
                              data: { confirm: 'You sure?' },
                              method: "delete",
                              :class => "btn btn-danger" %></p>
<%= link_to "Homepage", articles_path, :class => "btn btn-primary" %>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PhotoApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>



<div class="container">

  <div id="user_header">
    <% if current_user %>
      Logged in as <%= current_user.email %>
      <%= link_to "Log Out", logout_path %>
    <% else %>
      <%= link_to "Sign Up", signup_path %> or
      <%= link_to "Log In", login_path %>
    <% end %>
  </div>

  <%= flash[:notice] %>
  <%= flash[:alert] %>
  <%= yield %>
</div>

</body>
</html>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= render("layouts/errors", :object => @user) %>

<%= form_for @user do |f| %>
  <div class="form-group">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="form-group">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="form-group">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit "Sign Up" %>
  </div>
<% end %>